# Generated by Django 5.2.7 on 2025-10-24 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_city_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
    ]
