# Generated by Django 5.2.7 on 2025-10-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_alter_hotel_city_alter_hotelimage_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
